import Foundation

public enum HiTrendingLanguage {
    
    public static let programmings: [String: String] = [
        "1c-enterprise": "1C Enterprise",
        "abap": "ABAP",
        "abnf": "ABNF",
        "actionscript": "ActionScript",
        "ada": "Ada",
        "adobe-font-metrics": "Adobe Font Metrics",
        "agda": "Agda",
        "ags-script": "AGS Script",
        "alloy": "Alloy",
        "alpine-abuild": "Alpine Abuild",
        "ampl": "AMPL",
        "angelscript": "AngelScript",
        "ant-build-system": "Ant Build System",
        "antlr": "ANTLR",
        "apacheconf": "ApacheConf",
        "apex": "Apex",
        "api-blueprint": "API Blueprint",
        "apl": "APL",
        "apollo-guidance-computer": "Apollo Guidance Computer",
        "applescript": "AppleScript",
        "arc": "Arc",
        "asciidoc": "AsciiDoc",
        "asn.1": "ASN.1",
        "asp": "ASP",
        "aspectj": "AspectJ",
        "assembly": "Assembly",
        "ats": "ATS",
        "augeas": "Augeas",
        "autohotkey": "AutoHotkey",
        "autoit": "AutoIt",
        "awk": "Awk",
        "ballerina": "Ballerina",
        "batchfile": "Batchfile",
        "befunge": "Befunge",
        "bison": "Bison",
        "bitbake": "BitBake",
        "blade": "Blade",
        "blitzbasic": "BlitzBasic",
        "blitzmax": "BlitzMax",
        "bluespec": "Bluespec",
        "boo": "Boo",
        "brainfuck": "Brainfuck",
        "brightscript": "Brightscript",
        "bro": "Bro",
        "c": "C",
        "c%23": "C#",
        "c%2B%2B": "C++",
        "c-objdump": "C-ObjDump",
        "c2hs-haskell": "C2hs Haskell",
        "cap'n-proto": "Cap'n Proto",
        "cartocss": "CartoCSS",
        "ceylon": "Ceylon",
        "chapel": "Chapel",
        "charity": "Charity",
        "chuck": "ChucK",
        "cirru": "Cirru",
        "clarion": "Clarion",
        "clean": "Clean",
        "click": "Click",
        "clips": "CLIPS",
        "clojure": "Clojure",
        "closure-templates": "Closure Templates",
        "cmake": "CMake",
        "cobol": "COBOL",
        "coffeescript": "CoffeeScript",
        "coldfusion": "ColdFusion",
        "coldfusion-cfc": "ColdFusion CFC",
        "collada": "COLLADA",
        "common-lisp": "Common Lisp",
        "common-workflow-language": "Common Workflow Language",
        "component-pascal": "Component Pascal",
        "cool": "Cool",
        "coq": "Coq",
        "cpp-objdump": "Cpp-ObjDump",
        "creole": "Creole",
        "crystal": "Crystal",
        "cson": "CSON",
        "csound": "Csound",
        "csound-document": "Csound Document",
        "csound-score": "Csound Score",
        "css": "CSS",
        "csv": "CSV",
        "cuda": "Cuda",
        "cweb": "CWeb",
        "cycript": "Cycript",
        "cython": "Cython",
        "d": "D",
        "d-objdump": "D-ObjDump",
        "darcs-patch": "Darcs Patch",
        "dart": "Dart",
        "dataweave": "DataWeave",
        "desktop": "desktop",
        "diff": "Diff",
        "digital-command-language": "DIGITAL Command Language",
        "dm": "DM",
        "dns-zone": "DNS Zone",
        "dockerfile": "Dockerfile",
        "dogescript": "Dogescript",
        "dtrace": "DTrace",
        "dylan": "Dylan",
        "e": "E",
        "eagle": "Eagle",
        "easybuild": "Easybuild",
        "ebnf": "EBNF",
        "ec": "eC",
        "ecere-projects": "Ecere Projects",
        "ecl": "ECL",
        "eclipse": "ECLiPSe",
        "edje-data-collection": "Edje Data Collection",
        "edn": "edn",
        "eiffel": "Eiffel",
        "ejs": "EJS",
        "elixir": "Elixir",
        "elm": "Elm",
        "emacs-lisp": "Emacs Lisp",
        "emberscript": "EmberScript",
        "eq": "EQ",
        "erlang": "Erlang",
        "f%23": "F#",
        "factor": "Factor",
        "fancy": "Fancy",
        "fantom": "Fantom",
        "filebench-wml": "Filebench WML",
        "filterscript": "Filterscript",
        "fish": "fish",
        "flux": "FLUX",
        "formatted": "Formatted",
        "forth": "Forth",
        "fortran": "Fortran",
        "freemarker": "FreeMarker",
        "frege": "Frege",
        "g-code": "G-code",
        "game-maker-language": "Game Maker Language",
        "gams": "GAMS",
        "gap": "GAP",
        "gcc-machine-description": "GCC Machine Description",
        "gdb": "GDB",
        "gdscript": "GDScript",
        "genie": "Genie",
        "genshi": "Genshi",
        "gentoo-ebuild": "Gentoo Ebuild",
        "gentoo-eclass": "Gentoo Eclass",
        "gerber-image": "Gerber Image",
        "gettext-catalog": "Gettext Catalog",
        "gherkin": "Gherkin",
        "glsl": "GLSL",
        "glyph": "Glyph",
        "gn": "GN",
        "gnuplot": "Gnuplot",
        "go": "Go",
        "golo": "Golo",
        "gosu": "Gosu",
        "grace": "Grace",
        "gradle": "Gradle",
        "grammatical-framework": "Grammatical Framework",
        "graph-modeling-language": "Graph Modeling Language",
        "graphql": "GraphQL",
        "graphviz-(dot)": "Graphviz (DOT)",
        "groovy": "Groovy",
        "groovy-server-pages": "Groovy Server Pages",
        "hack": "Hack",
        "haml": "Haml",
        "handlebars": "Handlebars",
        "harbour": "Harbour",
        "haskell": "Haskell",
        "haxe": "Haxe",
        "hcl": "HCL",
        "hlsl": "HLSL",
        "html": "HTML",
        "html%2Bdjango": "HTML+Django",
        "html%2Becr": "HTML+ECR",
        "html%2Beex": "HTML+EEX",
        "html%2Berb": "HTML+ERB",
        "html%2Bphp": "HTML+PHP",
        "http": "HTTP",
        "hy": "Hy",
        "hyphy": "HyPhy",
        "idl": "IDL",
        "idris": "Idris",
        "igor-pro": "IGOR Pro",
        "inform-7": "Inform 7",
        "ini": "INI",
        "inno-setup": "Inno Setup",
        "io": "Io",
        "ioke": "Ioke",
        "irc-log": "IRC log",
        "isabelle": "Isabelle",
        "isabelle-root": "Isabelle ROOT",
        "j": "J",
        "jasmin": "Jasmin",
        "java": "Java",
        "java-server-pages": "Java Server Pages",
        "javascript": "JavaScript",
        "jflex": "JFlex",
        "jison": "Jison",
        "jison-lex": "Jison Lex",
        "jolie": "Jolie",
        "json": "JSON",
        "json5": "JSON5",
        "jsoniq": "JSONiq",
        "jsonld": "JSONLD",
        "jsx": "JSX",
        "julia": "Julia",
        "jupyter-notebook": "Jupyter Notebook",
        "kicad-layout": "KiCad Layout",
        "kicad-legacy-layout": "KiCad Legacy Layout",
        "kicad-schematic": "KiCad Schematic",
        "kit": "Kit",
        "kotlin": "Kotlin",
        "krl": "KRL",
        "labview": "LabVIEW",
        "lasso": "Lasso",
        "latte": "Latte",
        "lean": "Lean",
        "less": "Less",
        "lex": "Lex",
        "lfe": "LFE",
        "lilypond": "LilyPond",
        "limbo": "Limbo",
        "linker-script": "Linker Script",
        "linux-kernel-module": "Linux Kernel Module",
        "liquid": "Liquid",
        "literate-agda": "Literate Agda",
        "literate-coffeescript": "Literate CoffeeScript",
        "literate-haskell": "Literate Haskell",
        "livescript": "LiveScript",
        "llvm": "LLVM",
        "logos": "Logos",
        "logtalk": "Logtalk",
        "lolcode": "LOLCODE",
        "lookml": "LookML",
        "loomscript": "LoomScript",
        "lsl": "LSL",
        "lua": "Lua",
        "m": "M",
        "m4": "M4",
        "m4sugar": "M4Sugar",
        "makefile": "Makefile",
        "mako": "Mako",
        "markdown": "Markdown",
        "marko": "Marko",
        "mask": "Mask",
        "mathematica": "Mathematica",
        "matlab": "Matlab",
        "maven-pom": "Maven POM",
        "max": "Max",
        "maxscript": "MAXScript",
        "mediawiki": "MediaWiki",
        "mercury": "Mercury",
        "meson": "Meson",
        "metal": "Metal",
        "minid": "MiniD",
        "mirah": "Mirah",
        "modelica": "Modelica",
        "modula-2": "Modula-2",
        "module-management-system": "Module Management System",
        "monkey": "Monkey",
        "moocode": "Moocode",
        "moonscript": "MoonScript",
        "mql4": "MQL4",
        "mql5": "MQL5",
        "mtml": "MTML",
        "muf": "MUF",
        "mupad": "mupad",
        "myghty": "Myghty",
        "ncl": "NCL",
        "nearley": "Nearley",
        "nemerle": "Nemerle",
        "nesc": "nesC",
        "netlinx": "NetLinx",
        "netlinx%2Berb": "NetLinx+ERB",
        "netlogo": "NetLogo",
        "newlisp": "NewLisp",
        "nextflow": "Nextflow",
        "nginx": "Nginx",
        "nim": "Nim",
        "ninja": "Ninja",
        "nit": "Nit",
        "nix": "Nix",
        "nl": "NL",
        "nsis": "NSIS",
        "nu": "Nu",
        "numpy": "NumPy",
        "objdump": "ObjDump",
        "objective-c": "Objective-C",
        "objective-c%2B%2B": "Objective-C++",
        "objective-j": "Objective-J",
        "ocaml": "OCaml",
        "omgrofl": "Omgrofl",
        "ooc": "ooc",
        "opa": "Opa",
        "opal": "Opal",
        "opencl": "OpenCL",
        "openedge-abl": "OpenEdge ABL",
        "openrc-runscript": "OpenRC runscript",
        "openscad": "OpenSCAD",
        "opentype-feature-file": "OpenType Feature File",
        "org": "Org",
        "ox": "Ox",
        "oxygene": "Oxygene",
        "oz": "Oz",
        "p4": "P4",
        "pan": "Pan",
        "papyrus": "Papyrus",
        "parrot": "Parrot",
        "parrot-assembly": "Parrot Assembly",
        "parrot-internal-representation": "Parrot Internal Representation",
        "pascal": "Pascal",
        "pawn": "PAWN",
        "pep8": "Pep8",
        "perl": "Perl",
        "perl-6": "Perl 6",
        "php": "PHP",
        "pic": "Pic",
        "pickle": "Pickle",
        "picolisp": "PicoLisp",
        "piglatin": "PigLatin",
        "pike": "Pike",
        "plpgsql": "PLpgSQL",
        "plsql": "PLSQL",
        "pod": "Pod",
        "pogoscript": "PogoScript",
        "pony": "Pony",
        "postcss": "PostCSS",
        "postscript": "PostScript",
        "pov-ray-sdl": "POV-Ray SDL",
        "powerbuilder": "PowerBuilder",
        "powershell": "PowerShell",
        "processing": "Processing",
        "prolog": "Prolog",
        "propeller-spin": "Propeller Spin",
        "protocol-buffer": "Protocol Buffer",
        "public-key": "Public Key",
        "pug": "Pug",
        "puppet": "Puppet",
        "pure-data": "Pure Data",
        "purebasic": "PureBasic",
        "purescript": "PureScript",
        "python": "Python",
        "python-console": "Python console",
        "python-traceback": "Python traceback",
        "qmake": "QMake",
        "qml": "QML",
        "r": "R",
        "racket": "Racket",
        "ragel": "Ragel",
        "raml": "RAML",
        "rascal": "Rascal",
        "raw-token-data": "Raw token data",
        "rdoc": "RDoc",
        "realbasic": "REALbasic",
        "reason": "Reason",
        "rebol": "Rebol",
        "red": "Red",
        "redcode": "Redcode",
        "regular-expression": "Regular Expression",
        "ren'py": "Ren'Py",
        "renderscript": "RenderScript",
        "restructuredtext": "reStructuredText",
        "rexx": "REXX",
        "rhtml": "RHTML",
        "ring": "Ring",
        "rmarkdown": "RMarkdown",
        "robotframework": "RobotFramework",
        "roff": "Roff",
        "rouge": "Rouge",
        "rpc": "RPC",
        "rpm-spec": "RPM Spec",
        "ruby": "Ruby",
        "runoff": "RUNOFF",
        "rust": "Rust",
        "sage": "Sage",
        "saltstack": "SaltStack",
        "sas": "SAS",
        "sass": "Sass",
        "scala": "Scala",
        "scaml": "Scaml",
        "scheme": "Scheme",
        "scilab": "Scilab",
        "scss": "SCSS",
        "sed": "sed",
        "self": "Self",
        "shaderlab": "ShaderLab",
        "shell": "Shell",
        "shellsession": "ShellSession",
        "shen": "Shen",
        "slash": "Slash",
        "slim": "Slim",
        "smali": "Smali",
        "smalltalk": "Smalltalk",
        "smarty": "Smarty",
        "smt": "SMT",
        "solidity": "Solidity",
        "sourcepawn": "SourcePawn",
        "sparql": "SPARQL",
        "spline-font-database": "Spline Font Database",
        "sqf": "SQF",
        "sql": "SQL",
        "sqlpl": "SQLPL",
        "squirrel": "Squirrel",
        "srecode-template": "SRecode Template",
        "stan": "Stan",
        "standard-ml": "Standard ML",
        "stata": "Stata",
        "ston": "STON",
        "stylus": "Stylus",
        "sublime-text-config": "Sublime Text Config",
        "subrip-text": "SubRip Text",
        "sugarss": "SugarSS",
        "supercollider": "SuperCollider",
        "svg": "SVG",
        "swift": "Swift",
        "systemverilog": "SystemVerilog",
        "tcl": "Tcl",
        "tcsh": "Tcsh",
        "tea": "Tea",
        "terra": "Terra",
        "tex": "TeX",
        "text": "Text",
        "textile": "Textile",
        "thrift": "Thrift",
        "ti-program": "TI Program",
        "tla": "TLA",
        "toml": "TOML",
        "turing": "Turing",
        "turtle": "Turtle",
        "twig": "Twig",
        "txl": "TXL",
        "type-language": "Type Language",
        "typescript": "TypeScript",
        "unified-parallel-c": "Unified Parallel C",
        "unity3d-asset": "Unity3D Asset",
        "unix-assembly": "Unix Assembly",
        "uno": "Uno",
        "unrealscript": "UnrealScript",
        "urweb": "UrWeb",
        "vala": "Vala",
        "vcl": "VCL",
        "verilog": "Verilog",
        "vhdl": "VHDL",
        "vim-script": "Vim script",
        "visual-basic": "Visual Basic",
        "volt": "Volt",
        "vue": "Vue",
        "wavefront-material": "Wavefront Material",
        "wavefront-object": "Wavefront Object",
        "wdl": "wdl",
        "web-ontology-language": "Web Ontology Language",
        "webassembly": "WebAssembly",
        "webidl": "WebIDL",
        "wisp": "wisp",
        "world-of-warcraft-addon-data": "World of Warcraft Addon Data",
        "x10": "X10",
        "xbase": "xBase",
        "xc": "XC",
        "xcompose": "XCompose",
        "xml": "XML",
        "xojo": "Xojo",
        "xpages": "XPages",
        "xpm": "XPM",
        "xproc": "XProc",
        "xquery": "XQuery",
        "xs": "XS",
        "xslt": "XSLT",
        "xtend": "Xtend",
        "yacc": "Yacc",
        "yaml": "YAML",
        "yang": "YANG",
        "yara": "YARA",
        "zephir": "Zephir",
        "zimpl": "Zimpl",
    ]
    
    public static let spokens: [String: String] = [
        "ab": "Abkhazian",
        "aa": "Afar",
        "af": "Afrikaans",
        "ak": "Akan",
        "sq": "Albanian",
        "am": "Amharic",
        "ar": "Arabic",
        "an": "Aragonese",
        "hy": "Armenian",
        "as": "Assamese",
        "av": "Avaric",
        "ae": "Avestan",
        "ay": "Aymara",
        "az": "Azerbaijani",
        "bm": "Bambara",
        "ba": "Bashkir",
        "eu": "Basque",
        "be": "Belarusian",
        "bn": "Bengali",
        "bh": "Bihari languages",
        "bi": "Bislama",
        "bs": "Bosnian",
        "br": "Breton",
        "bg": "Bulgarian",
        "my": "Burmese",
        "ca": "Catalan, Valencian",
        "ch": "Chamorro",
        "ce": "Chechen",
        "ny": "Chichewa, Chewa, Nyanja",
        "zh": "Chinese",
        "cv": "Chuvash",
        "kw": "Cornish",
        "co": "Corsican",
        "cr": "Cree",
        "hr": "Croatian",
        "cs": "Czech",
        "da": "Danish",
        "dv": "Divehi, Dhivehi, Maldivian",
        "nl": "Dutch, Flemish",
        "dz": "Dzongkha",
        "en": "English",
        "eo": "Esperanto",
        "et": "Estonian",
        "ee": "Ewe",
        "fo": "Faroese",
        "fj": "Fijian",
        "fi": "Finnish",
        "fr": "French",
        "ff": "Fulah",
        "gl": "Galician",
        "ka": "Georgian",
        "de": "German",
        "el": "Greek, Modern",
        "gn": "Guarani",
        "gu": "Gujarati",
        "ht": "Haitian, Haitian Creole",
        "ha": "Hausa",
        "he": "Hebrew",
        "hz": "Herero",
        "hi": "Hindi",
        "ho": "Hiri Motu",
        "hu": "Hungarian",
        "ia": "Interlingua (International Auxil...",
        "id": "Indonesian",
        "ie": "Interlingue, Occidental",
        "ga": "Irish",
        "ig": "Igbo",
        "ik": "Inupiaq",
        "io": "Ido",
        "is": "Icelandic",
        "it": "Italian",
        "iu": "Inuktitut",
        "ja": "Japanese",
        "jv": "Javanese",
        "kl": "Kalaallisut, Greenlandic",
        "kn": "Kannada",
        "kr": "Kanuri",
        "ks": "Kashmiri",
        "kk": "Kazakh",
        "km": "Central Khmer",
        "ki": "Kikuyu, Gikuyu",
        "rw": "Kinyarwanda",
        "ky": "Kirghiz, Kyrgyz",
        "kv": "Komi",
        "kg": "Kongo",
        "ko": "Korean",
        "ku": "Kurdish",
        "kj": "Kuanyama, Kwanyama",
        "la": "Latin",
        "lb": "Luxembourgish, Letzeburgesch",
        "lg": "Ganda",
        "li": "Limburgan, Limburger, Limburgish",
        "ln": "Lingala",
        "lo": "Lao",
        "lt": "Lithuanian",
        "lu": "Luba-Katanga",
        "lv": "Latvian",
        "gv": "Manx",
        "mk": "Macedonian",
        "mg": "Malagasy",
        "ms": "Malay",
        "ml": "Malayalam",
        "mt": "Maltese",
        "mi": "Maori",
        "mr": "Marathi",
        "mh": "Marshallese",
        "mn": "Mongolian",
        "na": "Nauru",
        "nv": "Navajo, Navaho",
        "nd": "North Ndebele",
        "ne": "Nepali",
        "ng": "Ndonga",
        "nb": "Norwegian Bokmål",
        "nn": "Norwegian Nynorsk",
        "no": "Norwegian",
        "ii": "Sichuan Yi, Nuosu",
        "nr": "South Ndebele",
        "oc": "Occitan",
        "oj": "Ojibwa",
        "cu": "Church Slavic, Old Slavonic, Chu...",
        "om": "Oromo",
        "or": "Oriya",
        "os": "Ossetian, Ossetic",
        "pa": "Punjabi, Panjabi",
        "pi": "Pali",
        "fa": "Persian",
        "pl": "Polish",
        "ps": "Pashto, Pushto",
        "pt": "Portuguese",
        "qu": "Quechua",
        "rm": "Romansh",
        "rn": "Rundi",
        "ro": "Romanian, Moldavian, Moldovan",
        "ru": "Russian",
        "sa": "Sanskrit",
        "sc": "Sardinian",
        "sd": "Sindhi",
        "se": "Northern Sami",
        "sm": "Samoan",
        "sg": "Sango",
        "sr": "Serbian",
        "gd": "Gaelic, Scottish Gaelic",
        "sn": "Shona",
        "si": "Sinhala, Sinhalese",
        "sk": "Slovak",
        "sl": "Slovenian",
        "so": "Somali",
        "st": "Southern Sotho",
        "es": "Spanish, Castilian",
        "su": "Sundanese",
        "sw": "Swahili",
        "ss": "Swati",
        "sv": "Swedish",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "ti": "Tigrinya",
        "bo": "Tibetan",
        "tk": "Turkmen",
        "tl": "Tagalog",
        "tn": "Tswana",
        "to": "Tonga (Tonga Islands)",
        "tr": "Turkish",
        "ts": "Tsonga",
        "tt": "Tatar",
        "tw": "Twi",
        "ty": "Tahitian",
        "ug": "Uighur, Uyghur",
        "uk": "Ukrainian",
        "ur": "Urdu",
        "uz": "Uzbek",
        "ve": "Venda",
        "vi": "Vietnamese",
        "vo": "Volapük",
        "wa": "Walloon",
        "cy": "Welsh",
        "wo": "Wolof",
        "fy": "Western Frisian",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "yo": "Yoruba",
        "za": "Zhuang, Chuang",
        "zu": "Zulu",
    ]
    
    static let colors: [String: String] = [
        "1C Enterprise": "#814CCC",
        "ABAP": "#E8274B",
        "ABAP CDS": "#555e25",
        "ActionScript": "#882B0F",
        "Ada": "#02f88c",
        "Agda": "#315665",
        "AGS Script": "#B9D9FF",
        "AL": "#3AA2B5",
        "Alloy": "#64C800",
        "AMPL": "#E6EFBB",
        "AngelScript": "#C7D7DC",
        "ANTLR": "#9DC3FF",
        "Apex": "#1797c0",
        "API Blueprint": "#2ACCA8",
        "APL": "#5A8164",
        "Apollo Guidance Computer": "#0B3D91",
        "AppleScript": "#101F1F",
        "Arc": "#aa2afe",
        "ASP.NET": "#9400ff",
        "AspectJ": "#a957b0",
        "Assembly": "#6E4C13",
        "Asymptote": "#ff0000",
        "ATS": "#1ac620",
        "AutoHotkey": "#6594b9",
        "AutoIt": "#1C3552",
        "Ballerina": "#FF5000",
        "Batchfile": "#C1F12E",
        "Beef": "#a52f4e",
        "Bison": "#6A463F",
        "Blade": "#f7523f",
        "BlitzMax": "#cd6400",
        "Boo": "#d4bec1",
        "Boogie": "#c80fa0",
        "Brainfuck": "#2F2530",
        "Browserslist": "#ffd539",
        "C": "#555555",
        "C#": "#178600",
        "C++": "#f34b7d",
        "Ceylon": "#dfa535",
        "Chapel": "#8dc63f",
        "Cirru": "#ccccff",
        "Clarion": "#db901e",
        "Classic ASP": "#6a40fd",
        "Clean": "#3F85AF",
        "Click": "#E4E6F3",
        "Clojure": "#db5855",
        "Closure Templates": "#0d948f",
        "CoffeeScript": "#244776",
        "ColdFusion": "#ed2cd6",
        "ColdFusion CFC": "#ed2cd6",
        "Common Lisp": "#3fb68b",
        "Common Workflow Language": "#B5314C",
        "Component Pascal": "#B0CE4E",
        "Crystal": "#000100",
        "CSON": "#244776",
        "CSS": "#563d7c",
        "Cuda": "#3A4E3A",
        "D": "#ba595e",
        "Dafny": "#FFEC25",
        "Dart": "#00B4AB",
        "DataWeave": "#003a52",
        "Dhall": "#dfafff",
        "DM": "#447265",
        "Dockerfile": "#384d54",
        "Dogescript": "#cca760",
        "Dylan": "#6c616e",
        "E": "#ccce35",
        "eC": "#913960",
        "ECL": "#8a1267",
        "Eiffel": "#4d6977",
        "EJS": "#a91e50",
        "Elixir": "#6e4a7e",
        "Elm": "#60B5CC",
        "Emacs Lisp": "#c065db",
        "EmberScript": "#FFF4F3",
        "EQ": "#a78649",
        "Erlang": "#B83998",
        "F#": "#b845fc",
        "F*": "#572e30",
        "Factor": "#636746",
        "Fancy": "#7b9db4",
        "Fantom": "#14253c",
        "Faust": "#c37240",
        "FLUX": "#88ccff",
        "Forth": "#341708",
        "Fortran": "#4d41b1",
        "FreeMarker": "#0050b2",
        "Frege": "#00cafe",
        "Futhark": "#5f021f",
        "G-code": "#D08CF2",
        "Game Maker Language": "#71b417",
        "GAML": "#FFC766",
        "GDScript": "#355570",
        "Gemfile.lock": "#701516",
        "Genie": "#fb855d",
        "Gherkin": "#5B2063",
        "Glyph": "#c1ac7f",
        "Gnuplot": "#f0a9f0",
        "Go": "#00ADD8",
        "Golo": "#88562A",
        "Gosu": "#82937f",
        "Grammatical Framework": "#ff0000",
        "GraphQL": "#e10098",
        "Groovy": "#e69f56",
        "Hack": "#878787",
        "Haml": "#ece2a9",
        "Handlebars": "#f7931e",
        "Harbour": "#0e60e3",
        "Haskell": "#5e5086",
        "Haxe": "#df7900",
        "HiveQL": "#dce200",
        "HolyC": "#ffefaf",
        "HTML": "#e34c26",
        "Hy": "#7790B2",
        "IDL": "#a3522f",
        "Idris": "#b30000",
        "IGOR Pro": "#0000cc",
        "ImageJ Macro": "#99AAFF",
        "Io": "#a9188d",
        "Ioke": "#078193",
        "Isabelle": "#FEFE00",
        "J": "#9EEDFF",
        "Java": "#b07219",
        "JavaScript": "#f1e05a",
        "JFlex": "#DBCA00",
        "Jolie": "#843179",
        "jq": "#c7254e",
        "JSONiq": "#40d47e",
        "Jsonnet": "#0064bd",
        "Julia": "#a270ba",
        "Jupyter Notebook": "#DA5B0B",
        "Kaitai Struct": "#773b37",
        "Kotlin": "#F18E33",
        "KRL": "#28430A",
        "Lark": "#2980B9",
        "Lasso": "#999999",
        "Latte": "#f2a542",
        "Less": "#1d365d",
        "Lex": "#DBCA00",
        "LFE": "#4C3023",
        "Liquid": "#67b8de",
        "LiveScript": "#499886",
        "LLVM": "#185619",
        "LOLCODE": "#cc9900",
        "LookML": "#652B81",
        "LSL": "#3d9970",
        "Lua": "#000080",
        "Macaulay2": "#d8ffff",
        "Makefile": "#427819",
        "Markdown": "#083fa1",
        "Marko": "#42bff2",
        "Mask": "#f97732",
        "MATLAB": "#e16737",
        "Max": "#c4a79c",
        "MAXScript": "#00a6a6",
        "mcfunction": "#E22837",
        "Mercury": "#ff2b2b",
        "Meson": "#007800",
        "Metal": "#8f14e9",
        "Mirah": "#c7a938",
        "mIRC Script": "#3d57c3",
        "MLIR": "#5EC8DB",
        "Modula-3": "#223388",
        "MQL4": "#62A8D6",
        "MQL5": "#4A76B8",
        "MTML": "#b7e1f4",
        "Mustache": "#724b3b",
        "NCL": "#28431f",
        "Nearley": "#990000",
        "Nemerle": "#3d3c6e",
        "nesC": "#94B0C7",
        "NetLinx": "#0aa0ff",
        "NetLinx+ERB": "#747faa",
        "NetLogo": "#ff6375",
        "NewLisp": "#87AED7",
        "Nextflow": "#3ac486",
        "Nim": "#ffc200",
        "Nit": "#009917",
        "Nix": "#7e7eff",
        "Nu": "#c9df40",
        "NumPy": "#9C8AF9",
        "Nunjucks": "#3d8137",
        "NWScript": "#111522",
        "Objective-C": "#438eff",
        "Objective-C++": "#6866fb",
        "Objective-J": "#ff0c5a",
        "ObjectScript": "#424893",
        "OCaml": "#3be133",
        "Odin": "#60AFFE",
        "Omgrofl": "#cabbff",
        "ooc": "#b0b77e",
        "Opal": "#f7ede0",
        "OpenQASM": "#AA70FF",
        "Org": "#77aa99",
        "Oxygene": "#cdd0e3",
        "Oz": "#fab738",
        "P4": "#7055b5",
        "Pan": "#cc0000",
        "Papyrus": "#6600cc",
        "Parrot": "#f3ca0a",
        "Pascal": "#E3F171",
        "Pawn": "#dbb284",
        "Pep8": "#C76F5B",
        "Perl": "#0298c3",
        "PHP": "#4F5D95",
        "PigLatin": "#fcd7de",
        "Pike": "#005390",
        "PLSQL": "#dad8d8",
        "PogoScript": "#d80074",
        "PostScript": "#da291c",
        "PowerBuilder": "#8f0f8d",
        "PowerShell": "#012456",
        "Prisma": "#0c344b",
        "Processing": "#0096D8",
        "Prolog": "#74283c",
        "Propeller Spin": "#7fa2a7",
        "Pug": "#a86454",
        "Puppet": "#302B6D",
        "PureBasic": "#5a6986",
        "PureScript": "#1D222D",
        "Python": "#3572A5",
        "q": "#0040cd",
        "Q#": "#fed659",
        "QML": "#44a51c",
        "Qt Script": "#00b841",
        "Quake": "#882233",
        "R": "#198CE7",
        "Racket": "#3c5caa",
        "Ragel": "#9d5200",
        "Raku": "#0000fb",
        "RAML": "#77d9fb",
        "Rascal": "#fffaa0",
        "Reason": "#ff5847",
        "Rebol": "#358a5b",
        "Record Jar": "#0673ba",
        "Red": "#f50000",
        "Ren'Py": "#ff7f7f",
        "ReScript": "#ed5051",
        "Ring": "#2D54CB",
        "Riot": "#A71E49",
        "Roff": "#ecdebe",
        "Rouge": "#cc0088",
        "Ruby": "#701516",
        "RUNOFF": "#665a4e",
        "Rust": "#dea584",
        "SaltStack": "#646464",
        "SAS": "#B34936",
        "Sass": "#a53b70",
        "Scala": "#c22d40",
        "Scaml": "#bd181a",
        "Scheme": "#1e4aec",
        "SCSS": "#c6538c",
        "sed": "#64b970",
        "Self": "#0579aa",
        "Shell": "#89e051",
        "Shen": "#120F14",
        "Slash": "#007eff",
        "Slice": "#003fa2",
        "Slim": "#2b2b2b",
        "Smalltalk": "#596706",
        "SmPL": "#c94949",
        "Solidity": "#AA6746",
        "SourcePawn": "#f69e1d",
        "SQF": "#3F3F3F",
        "Squirrel": "#800000",
        "SRecode Template": "#348a34",
        "Stan": "#b2011d",
        "Standard ML": "#dc566d",
        "Starlark": "#76d275",
        "Stylus": "#ff6347",
        "SuperCollider": "#46390b",
        "Svelte": "#ff3e00",
        "SVG": "#ff9900",
        "Swift": "#ffac45",
        "SystemVerilog": "#DAE1C2",
        "Tcl": "#e4cc98",
        "Terra": "#00004c",
        "TeX": "#3D6117",
        "TI Program": "#A0AA87",
        "Turing": "#cf142b",
        "Twig": "#c1d026",
        "TypeScript": "#2b7489",
        "Unified Parallel C": "#4e3617",
        "Uno": "#9933cc",
        "UnrealScript": "#a54c4d",
        "V": "#4f87c4",
        "Vala": "#fbe5cd",
        "VBA": "#867db1",
        "VBScript": "#15dcdc",
        "VCL": "#148AA8",
        "Verilog": "#b2b7f8",
        "VHDL": "#adb2cb",
        "Vim script": "#199f4b",
        "Visual Basic .NET": "#945db7",
        "Volt": "#1F1F1F",
        "Vue": "#2c3e50",
        "wdl": "#42f1f4",
        "WebAssembly": "#04133b",
        "wisp": "#7582D1",
        "Wollok": "#a23738",
        "X10": "#4B6BEF",
        "xBase": "#403a40",
        "XC": "#99DA07",
        "XQuery": "#5232e7",
        "XSLT": "#EB8CEB",
        "Yacc": "#4B6C4B",
        "YAML": "#cb171e",
        "YARA": "#220000",
        "YASnippet": "#32AB90",
        "ZAP": "#0d665e",
        "ZenScript": "#00BCD1",
        "Zephir": "#118f9e",
        "Zig": "#ec915c",
        "ZIL": "#dc75e5",
    ]
    
}
